/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BotManagerJNI */

#ifndef _Included_BotManagerJNI
#define _Included_BotManagerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BotManagerJNI
 * Method:    nativeNew
 * Signature: (LhasWaveEnded_func;)J
 */
JNIEXPORT jlong JNICALL Java_BotManagerJNI_nativeNew
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
