/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GeneticBotJNI */

#ifndef _Included_GeneticBotJNI
#define _Included_GeneticBotJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GeneticBotJNI
 * Method:    nativeNew
 * Signature: (Ljava/util/List;)J
 */
JNIEXPORT jlong JNICALL Java_GeneticBotJNI_nativeNew
  (JNIEnv *, jobject, jobject);

/*
 * Class:     GeneticBotJNI
 * Method:    getValuesUnder
 * Signature: (Ljava/util/List;I)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_GeneticBotJNI_getValuesUnder
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
