/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../Dependencies/include/include/jni.h"
/* Header for class TowerManagerJNI */

#ifndef _Included_TowerManagerJNI
#define _Included_TowerManagerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TowerManagerJNI
 * Method:    nativeNew
 * Signature: (Ljava/util/List;Ljava/util/List;Ljava/util/List;)J
 */
JNIEXPORT jlong JNICALL Java_TowerManagerJNI_nativeNew
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
